/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import javax.swing.JOptionPane;
import rede.AtorJogador;
import rede.EstadoDoJogo;
/**
 *
 * @author Vitor
 */
public class TelaPrincipal extends javax.swing.JFrame {
    //criar botao desistir
    protected AtorJogador atorJogador;
    protected boolean estaConectado;
    protected boolean partidaIniciada;
    
    public TelaPrincipal(AtorJogador atorJogador) {
        this.atorJogador = atorJogador;
        initComponents();
    }
     
    public void exibeTela() {
        setResizable(false);
        setVisible(true);
    }
    
    public boolean getPartidaIniciada() {
        return partidaIniciada;
    }
    
    public void setPartidaIniciada(boolean partidaIniciou) {
        partidaIniciada = partidaIniciou;
    }

    public boolean setEstaConectado(boolean conectou){
        return estaConectado = true;
    }
  
    public boolean estaConectado()
    {
        return estaConectado;
    }
    
    public void showDialog(String msg) {
        JOptionPane.showMessageDialog(this, msg);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelBatalhaMedieval = new javax.swing.JLabel();
        jButtonDesistir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConectar = new javax.swing.JMenu();
        jMenuEscolherPersonagem = new javax.swing.JMenu();
        jMenuIniciarJornada = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMaximumSize(getPreferredSize());
        jPanel1.setMinimumSize(getPreferredSize());

        jLabel1.setText("1º: Conectar");

        jLabel2.setText("2º: Escolher personagem");

        jLabel3.setText("3º: Esperar adversário conectar");

        jLabel4.setText("4º: Iniciar Jornada");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel5.setText("Bem-vindo ao Batalha Medieval");

        jLabelBatalhaMedieval.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/batalha_medieval.jpg"))); // NOI18N

        jButtonDesistir.setText("Desistir");
        jButtonDesistir.setEnabled(false);
        jButtonDesistir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDesistirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 388, Short.MAX_VALUE)
                        .addComponent(jButtonDesistir)))
                .addGap(54, 54, 54))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addComponent(jLabelBatalhaMedieval)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(29, 29, 29)
                .addComponent(jLabelBatalhaMedieval)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jButtonDesistir))
                .addGap(26, 26, 26))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jMenuConectar.setText("Conectar");
        jMenuConectar.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuConectarMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuConectar);

        jMenuEscolherPersonagem.setText("Escolher Personagem");
        jMenuEscolherPersonagem.setEnabled(false);
        jMenuEscolherPersonagem.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuEscolherPersonagemMenuSelected(evt);
            }
        });
        jMenuEscolherPersonagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEscolherPersonagemMouseClicked(evt);
            }
        });
        jMenuEscolherPersonagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuEscolherPersonagemActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenuEscolherPersonagem);

        jMenuIniciarJornada.setText("Iniciar Jornada");
        jMenuIniciarJornada.setEnabled(false);
        jMenuIniciarJornada.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenuIniciarJornadaMenuSelected(evt);
            }
        });
        jMenuBar1.add(jMenuIniciarJornada);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuEscolherPersonagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuEscolherPersonagemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEscolherPersonagemActionPerformed

    private void jMenuEscolherPersonagemMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuEscolherPersonagemMenuSelected
        // TODO add your handling code here:
        TelaEscolhaPersonagem escolhaPersonagem = new TelaEscolhaPersonagem(this.atorJogador);
        this.atorJogador.exibeTelaPersonagem();
        jMenuEscolherPersonagem.setEnabled(false);
        jMenuIniciarJornada.setEnabled(true);
    }//GEN-LAST:event_jMenuEscolherPersonagemMenuSelected

    private void jMenuEscolherPersonagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEscolherPersonagemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuEscolherPersonagemMouseClicked

    public String showNameQuestion() {
	return JOptionPane.showInputDialog(this, "Escolha seu nome:");
    }
   
    private void jMenuConectarMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuConectarMenuSelected
        // TODO add your handling code here:
        if(this.estaConectado()==false)
            this.atorJogador.conectar();
        if(this.estaConectado())
            jMenuEscolherPersonagem.setEnabled(true);
        else
            jMenuEscolherPersonagem.setEnabled(false);
        if(this.estaConectado())
            jMenuConectar.setEnabled(false);
        else
            jMenuConectar.setEnabled(true);
    }//GEN-LAST:event_jMenuConectarMenuSelected

    private void jMenuIniciarJornadaMenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenuIniciarJornadaMenuSelected
        // TODO add your handling code here:
        this.atorJogador.iniciarPartidaPedido();
//        if(this.getPartidaIniciada()){
////            JOptionPane.showMessageDialog(null, "Partida já iniciada pelo adversário, espere ele concluir a jogada.");
//            TelaJornada telaJornada = new TelaJornada(atorJogador);
//            atorJogador.exibeTelaJornada();
//            jButtonDesistir.setEnabled(true);
//        }
//        else{
//            this.atorJogador.iniciarPartidaPedido();
//            if(this.getPartidaIniciada()){
//                TelaJornada telaJornada = new TelaJornada(atorJogador);
//                atorJogador.exibeTelaJornada();
//                jButtonDesistir.setEnabled(true);
//            }
//        }
    }//GEN-LAST:event_jMenuIniciarJornadaMenuSelected

    private void jButtonDesistirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDesistirActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(this, "Tem certeza de que deseja se render?", "Fechar jogo", JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
                atorJogador.desistir();
        }
    }//GEN-LAST:event_jButtonDesistirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDesistir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelBatalhaMedieval;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConectar;
    private javax.swing.JMenu jMenuEscolherPersonagem;
    private javax.swing.JMenu jMenuIniciarJornada;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

   
}
