/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Random;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.Jogador;
import rede.AtorJogador;

/**
 *
 * @author Vitor
 */
public class TelaJornada extends javax.swing.JFrame {

    protected AtorJogador atorJogador;
    protected DefaultListModel model = new DefaultListModel();
    protected int cliques = 0;
    public Jogador jogador;

    public TelaJornada(AtorJogador ator) {
        this.atorJogador = ator;
        initComponents();
        jListItens.setModel(model);
    }

    public void exibeTela() {
        setResizable(false);
        setVisible(true);
        inicializaJogador();
    }

    private void inicializaJogador() {
        this.jogador = this.atorJogador.getJogador();
    }

    public void setRandomItem(int numeroRandom, int cliques) {
        if(cliques==1){
            if (numeroRandom == 1) {
                this.jogador.getPersonagem().setItem1("ataque", 10);
            }
            if (numeroRandom == 2) {
                this.jogador.getPersonagem().setItem1("defesa", 10);
            }
            if (numeroRandom == 3) {
                this.jogador.getPersonagem().setItem1("vida", 10);
            }
        }
        if(cliques==2){
            if (numeroRandom == 1) {
                this.jogador.getPersonagem().setItem2("ataque", 10);
            }
            if (numeroRandom == 2) {
                this.jogador.getPersonagem().setItem2("defesa", 10);
            }
            if (numeroRandom == 3) {
                this.jogador.getPersonagem().setItem2("vida", 10);
            }
        }if(cliques==3){
            if (numeroRandom == 1) {
                this.jogador.getPersonagem().setItem3("ataque", 10);
            }
            if (numeroRandom == 2) {
                this.jogador.getPersonagem().setItem3("defesa", 10);
            }
            if (numeroRandom == 3) {
                this.jogador.getPersonagem().setItem3("vida", 10);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBoxCaminho = new javax.swing.JComboBox<>();
        jLabelEscolhaUmCaminho = new javax.swing.JLabel();
        Mochila = new javax.swing.JLabel();
        jButtonIr = new javax.swing.JButton();
        jLabelVinculadoImagem = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListItens = new javax.swing.JList<>();
        jButtonBatalhar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela Jornada");

        jComboBoxCaminho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Norte", "Sul", "Leste", "Oeste" }));

        jLabelEscolhaUmCaminho.setText("Escolha um caminho:");

        Mochila.setText("Mochila");

        jButtonIr.setText("Ir");
        jButtonIr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIrActionPerformed(evt);
            }
        });

        jLabelVinculadoImagem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/caminho.jpg"))); // NOI18N

        jListItens.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jListItens);

        jButtonBatalhar.setText("Batalhar");
        jButtonBatalhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBatalharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelVinculadoImagem, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabelEscolhaUmCaminho)
                        .addGap(35, 35, 35)
                        .addComponent(jComboBoxCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonIr)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(Mochila))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jButtonBatalhar)))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEscolhaUmCaminho)
                    .addComponent(jComboBoxCaminho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonIr))
                .addGap(18, 18, 18)
                .addComponent(jLabelVinculadoImagem)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(Mochila)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jButtonBatalhar)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIrActionPerformed
        // TODO add your handling code here:
        cliques++;
        if (cliques > 3) {
            JOptionPane.showMessageDialog(null, "Você atingiu o número máximo de itens.");
        } else {
            Random r = new Random();
            int numeroRandom = r.nextInt(3) + 1;
            setRandomItem(numeroRandom, cliques);
            if (numeroRandom == 1) {
                ImageIcon pocaoAtaque = new ImageIcon(TelaJornada.class.getResource("/images/pocao_ataque.png"));
                JOptionPane.showMessageDialog(null, "", "Você encontrou uma poção de ataque!", JOptionPane.INFORMATION_MESSAGE, pocaoAtaque);
                model.addElement(String.format("poção de ataque"));
            }
            if (numeroRandom == 2) {
                ImageIcon pocaoDefesa = new ImageIcon(TelaJornada.class.getResource("/images/pocao_defesa.png"));
                JOptionPane.showMessageDialog(null, "", "Você encontrou uma poção de defesa!", JOptionPane.INFORMATION_MESSAGE, pocaoDefesa);
                model.addElement(String.format("poção de defesa"));
            }
            if (numeroRandom == 3) {
                ImageIcon pocaoVida = new ImageIcon(TelaJornada.class.getResource("/images/pocao_vida.png"));
                JOptionPane.showMessageDialog(null, "", "Você encontrou uma poção de vida!", JOptionPane.INFORMATION_MESSAGE, pocaoVida);
                model.addElement(String.format("poção de vida"));
            }
        }
    }//GEN-LAST:event_jButtonIrActionPerformed

    private void jButtonBatalharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBatalharActionPerformed
        // TODO add your handling code here:
        this.atorJogador.enviarEstado();
        this.dispose();
        TelaBatalha telaBatalha = new TelaBatalha(this.atorJogador);
//        this.atorJogador.enviarEstado();
    }//GEN-LAST:event_jButtonBatalharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mochila;
    private javax.swing.JButton jButtonBatalhar;
    private javax.swing.JButton jButtonIr;
    private javax.swing.JComboBox<String> jComboBoxCaminho;
    private javax.swing.JLabel jLabelEscolhaUmCaminho;
    private javax.swing.JLabel jLabelVinculadoImagem;
    private javax.swing.JList<String> jListItens;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
